# Use Eclipse Temurin JDK for better platform compatibility
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY target/api-gateway-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8765
ENTRYPOINT ["java", "-jar", "app.jar"]
